CREATE TABLE IF NOT EXISTS pauta (
    id SERIAL PRIMARY KEY,
    uuid UUID UNIQUE NOT NULL,
    titulo VARCHAR(100) UNIQUE NOT NULL,
    descricao VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cooperado (
     id SERIAL PRIMARY KEY,
     uuid UUID UNIQUE NOT NULL,
     nome VARCHAR(100) NOT NULL,
     cpf VARCHAR(11) UNIQUE NOT NULL,
     created_at TIMESTAMP NOT NULL DEFAULT NOW(),
     updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);