@startuml
Frontend -> ReadPautaController: GET /v1/pautas
ReadPautaController -> ServicedBus: ListAllPautasQuery
ServicedBus -> ServicedBus : try: exec event
ServicedBus -> ListAllPautasResolver: ListAllPautasQuery
ListAllPautasResolver -> ReadPautaRepository
ReadPautaRepository -> DATABASE: findAll()
DATABASE -> ReadPautaRepository: List<PautaInDto>
ReadPautaRepository -> ListAllPautasResolver: List<PautaInDto>
ListAllPautasResolver -> ServicedBus: List<PautaInDto>
ServicedBus -> ReadPautaController: ListAllPautasQuery
ReadPautaController -> ReadPautaController: query.getResult()
ReadPautaController -> Frontend: HTTP 200: Json Result
@enduml