@startuml
Frontend -> PautaController: GET /v1/pautas
PautaController -> ReadPautaRepository
ReadPautaRepository -> DATABASE: select statement
DATABASE -> ReadPautaRepository
ReadPautaRepository -> PautaController: List<PautaDTO>
PautaController --> Frontend: HTTP 200 ok
PautaController -> Frontend: JSON
@enduml