@startuml
Frontend -> ReadPautaController: GET /v1/pautas
ReadPautaController -> ReadPautaRepository
ReadPautaRepository -> DATABASE: select statement
DATABASE -> ReadPautaRepository
ReadPautaRepository -> ReadPautaController: List<PautaDTO>
ReadPautaController --> Frontend: HTTP 200 ok
ReadPautaController -> Frontend: JSON
@enduml