@startuml
Frontend -> WritePautaController: JSON Payload
WritePautaController -> CommandBus: CreatePautaCommand
CommandBus -> CreatePautaCommandHandler: CreatePautaCommand
CreatePautaCommandHandler -> WritePautaRepository: Pauta
WritePautaRepository -> DATABASE: create statement
DATABASE -> WritePautaRepository
WritePautaRepository -> CreatePautaCommandHandler
CreatePautaCommandHandler -> CommandBus
CommandBus -> WritePautaController
CommandBus --> CommandBus: EventPublisher::CommandEvent
WritePautaController -> Frontend: HTTP 201 created
@enduml