@startuml
Frontend -> WritePautaController: JSON Payload
WritePautaController -> ServicedBus: CreatePautaCommand
ServicedBus -> CreatePautaHandler: CreatePautaCommand
CreatePautaHandler -> WritePautaRepository: Pauta
WritePautaRepository -> DATABASE: create statement
DATABASE -> WritePautaRepository
WritePautaRepository -> CreatePautaHandler
CreatePautaHandler -> ServicedBus
ServicedBus -> WritePautaController
ServicedBus --> ServicedBus: EventPublisher::CommandEvent
WritePautaController -> Frontend: HTTP 201 created
@enduml